### ISSUE TITLE
Is this toolkit still working?

### ISSUE THREAD

**Issue by Ziriax** [3DStreamingToolkit/3DStreamingToolkit#304]
I tried running this amazing toolkit, locally, on my LAN, using Windows 10 Pro x64.

I installed the source code for VS2017, and I'm able to compile everything.

I run your signalling server using 

`docker run --rm -it -p 3000:3000 -e WEBRTC_CORS=1 -e WEBRTC_SIGNAL_LOGGING=1 3dtoolkit-signal`

That runs fine (although I can't get the heartbeat enabled, that gives an `timeoutAt` exception, see below)

Since I'm running in a LAN, I disabled all ICE, STUN and TURN, and auth servers, using the config

```json
{
  "iceConfiguration": "none",
  "turnServer": {
    "uri": "turn:turnserveruri:5349",
    "username": "username",
    "password": "password"
  },
  "serverUri": "http://localhost",
  "port": 3000,
  "heartbeat": 5000,
  "authentication": {
    "authorityUri": "",
    "resource": "00000000-0000-0000-0000-000000000000",
    "clientId": "00000000-0000-0000-0000-000000000000",
    "clientSecret": "aadsecretstring"
  }
}
```

I start the `SpinningCubeServer` server, then I run the `WebClient`, I connect the latter, double click on the server window to start the 3D rendering, a `Disconnect` button is shown, and everything should work (no errors are printed modulus the `heartbeat` stuff), but nothing appears on screen....  

When I drag the mouse on the HTML video element, the transform message is passed.

I tried all browsers, Firefox, Edge, Chrome.

I put a breakpoint in the server where `BufferCapturer::SendFrame(frame);` is called, and that breaks, no errors are thrown. 

What could I do to debug this? 

EDIT:

It now works, kinda ! In `app.js` I changed the transport policy to all:

```
var pcConfigNone = {
    'iceServers': [],
    'iceTransportPolicy': 'all'
  }
```

Then still nothing is rendered, but when I not drag the mouse, sometimes I get a black screen, and when holding down control and very carefully moving the mouse, I see a rotating cube.

So something is not yet 100%, but it does kinda work :-)

_Signal server exception when enabling heartbeat:_

```
TypeError: Cannot set property 'timeoutAt' of undefined
    at TimeoutPeerList.refreshPeerTimeout (/usr/src/app/signal/node_modules/webrtc-signal-http-heartbeat/lib/index.js:38:35)
    at router.get (/usr/src/app/signal/node_modules/webrtc-signal-http-heartbeat/lib/index.js:79:27)
    at Layer.handle [as handle_request] (/usr/src/app/signal/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/signal/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/signal/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/signal/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/signal/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/signal/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/signal/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/src/app/signal/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/signal/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/src/app/signal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/signal/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/signal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/signal/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/signal/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/signal/node_modules/express-bunyan-logger/index.js:197:9
    at /usr/src/app/signal/node_modules/express-bunyan-logger/index.js:12:9
    at Layer.handle [as handle_request] (/usr/src/app/signal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/signal/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/signal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/signal/node_modules/express/lib/router/index.js:335:12)
```

**Comment by anderm** [comment]
Hi @Ziriax - for any future issues, please use our template. 

To answer the first question, yes! this toolkit is working very well 😃 There are quite a few moving parts but you are very close. This issue is similar to #305, your webclient needs to have a public STUN in the configuration. For the web client we already have a configuration for this exact scenario:
```
  var pcConfigSTUNStatic = {
    'iceServers': [{
      'urls': 'stun:stun.l.google.com:19302'
    }]
  };
```
To enable the static STUN, modify the `app.js` at line 271 : 
```
          'peerConnectionConfig': pcConfigSTUNStatic
```
This will ensure the web client will use the same STUN server and establish the connection. You should see the video feed working at this point. Let us know if you still have issues!

**Comment by Ziriax** [comment]
I think I'm seeing a latency of about 30ms on a single machine, I was hoping to get a latency of max one frame when rendering at 60FPS, like Newtek's NDI, that actually can have a latency of about 16 scan lines, but that is impossible with 3D rendering, since one always has to render a frame before transmitting it, unless one creates a scanline renderer, and transmits on the fly ;-)

Out of curiosity, how to you measure the latency? Do you have tools for that?

Again, thanks a lot for this toolkit, amazing job

**Comment by ValentinKraft** [comment]
for me, after days of setup, the only thing that I got to work was the DirectX Server and Client example. To my mind, the whole Toolkit is way too clumsy and not well maintained (e.g. most of the scripts fail).

**Comment by tylergibson** [comment]
@Ziriax - You can measure latency most easily using a web client in Chrome and using chrome://webrtc-internals/ - gives you a whirlwind of debugging and performance information.

On local networks, total round trip time should be sub 10ms (and usually is 3-5ms).  On remote installations round trip time will vary depending on your configuration and physical distance from server.  Rule of thumb is 100miles == 2ms of additional latency for rough estimates of round trip.

@ValentinKraft really sorry you've had a poor experience with the toolkit.  You are correct that there are a lot of moving pieces and it is quite a complex area (imagine how hard it was before the toolkit!).    It really is designed as a toolkit for developers to build their own solutions, not as a solution by itself.

**Comment by hcglhcgl** [comment]
Did anyone manage to fix the signal server exception when enabling heartbeat?

**Comment by eirikwah** [comment]
@hcglhcgl , as "tylergibson" stated:
> You are correct that there are a lot of moving pieces and it is quite a complex area (imagine how hard it was before the toolkit!). It really is designed as a toolkit for developers to build their own solutions, not as a solution by itself.

We have used 3DSTK, including the signalling server, as a starting point for our own project. We were a bit disappointed because we thought that the 3DSTK was a more finished/polished software package. However; using this project as a starting point has given our own project a solid boost, and it has saved us from a lot of work.

Finally, to directly answer your specific question: We god the signalling server to work with heartbeats, but only after a complete re-write. I am sorry to say that I am not entitled to share this code (at leat not yet).
